<a href="https://colab.research.google.com/github/mujahidrj/Artificial-Intelligence/blob/master/HW4/HW4_Question_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

# 2-D Convolution

In [0]:
import numpy as np

In [0]:
def conv2d(input_mat: np.array, kernel_mat: np.array) -> np.array:

  # Checks to see if the input matrix and kernel matrix are square
  if input_mat.shape[0] != input_mat.shape[1]:
    raise Exception("Please enter a square Input Matrix!")
  if kernel_mat.shape[0] != kernel_mat.shape[1]:
    raise Exception("Please enter a square Kernel Matrix!")

  # Checks to see if the kernel matrix is bigger than the input matrix
  if kernel_mat.shape[0] > input_mat.shape[0]:
     raise Exception("Kernel shape is greater than input matrix shape.")

  # flip kernel
  kernel_mat = np.flipud(np.fliplr(kernel_mat))

  output_mat = np.zeros((input_mat.shape[0]-kernel_mat.shape[0]+1, input_mat.shape[1]-kernel_mat.shape[1]+1))
  for i in range(0, output_mat.shape[0]):
    for y in range(0, output_mat.shape[1]):
      for k in range(0, kernel_mat.shape[0]):
        for l in range(0, kernel_mat.shape[1]):
          output_mat[i][y] += input_mat[i+k][y+l]*kernel_mat[k][l]
  return output_mat


# Test Cases Provided by Dr. Wocjan

In [42]:
input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either throw an error, or return None
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(None)

for i in range(len(input_mat)):
  try:
    # Modify code so conv2d will run the testcases.
    output_mat = conv2d(input_mat[i], kernel_mat[i])
    print(output_mat)
  except Exception as e:
    print(e)
    output_mat = None
  finally:
    if np.array_equal(output_mat, expected_mat[i]):
      print("Correct output!\n")
    else:
      print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

Kernel shape is greater than input matrix shape.
Correct output!



# Extra Cases

In [43]:
input_mat = []
kernel_mat = []
expected_mat = []

# test case 6
input_mat = np.ones(shape=(11,11))

kernel_mat = np.identity(5)

# returns matrix of all 5's
print(conv2d(input_mat, kernel_mat))
print()

# test case 7 - non-square matrix for one of the parameters should fail.
input_mat = np.array([[1, 2, 1],
                           [1, 1, 3]])

kernel_mat = np.array([[1, 0],
                            [0, 1]])

try:
  output_mat = conv2d(input_mat, kernel_mat)
  print(output_mat)
except Exception as e:
  print(e)
print()

# test case 8
input_mat = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
kernel_mat = np.array([[1,0],
              [0,2]])

print(conv2d(input_mat, kernel_mat))

[[5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]

Please enter a square Input Matrix!

[[ 7. 10.]
 [16. 19.]]
