<a href="https://colab.research.google.com/github/mujahidrj/Artificial-Intelligence/blob/master/HW4/HW4_Question_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 2

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
import numpy as np

In [0]:
def maxpooling2d(input_mat, s):
  
  if input_mat.shape[0] != input_mat.shape[1]:
    raise Exception("Please enter a square Input Matrix!")

  if s > input_mat.shape:
    raise Exception("Stride bigger than matrix!")
  
  # Uses integer division to get the size of the output matrix based on the width and length divided by the stride
  output_mat = np.zeros((input_mat.shape[0]//s, input_mat.shape[1]//s))

  # Increments by stride where i and j loop correspond to width and length 
  for i in range(0, output_mat.shape[0], s):
    for j in range(0, output_mat.shape[1], s):
      output_mat[i//s][j//s] = input_mat[i][j]
      for k in range(0, s):
        for l in range(0, s):
          # Take the max of every region and put it in the output matrix 
          output_mat[i//s][j//s] = max(input_mat[i+k][j+l], output_mat[i//s][j//s])


  return output_mat

# Test Cases Provided by Dr. Wocjan

In [3]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  #output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
