<a href="https://colab.research.google.com/github/mujahidrj/Artificial-Intelligence/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW 1 Details:

Inside a colab notebook implement a Python function multiply_matrices that takes as input a list of numpy arrays and outputs their product. It should raise a custom exception if there is a pair of incompatible matrices. The exception message should provide information about which pair of matrices is bad. Make sure that you follow the style guide for Python. Also use simple markup for formatting your notebook and include a simple description of what your program does inside a text cell. You should also use some simple Latex commands, for instance, when explaining what it means for two matrices to be compatible.

**Description**: 

The following program includes a function called multiply_matrices, which takes in a list of numpy arrays and then performs matrix multiplication on them if they are compatible. If they are incompatible, an exception will be thrown and will return the incompatible matrices. Test cases are below as well as a short description of how matrix multiplication works using Latex commands:

In [0]:


import numpy as np
 
# Takes in a list of numpy arrays
def multiply_matrices(npArrays):

  if len(npArrays) == 0:
    print("Empty Array")
    return None
  
  if len(npArrays) == 1:
    return array[0]

  # Gets the identity matrix where all diagonals are 1 and everything else is 0
  res = np.identity(npArrays[0].shape[0], int)
  #print (res)
  i = 0;

  # Goes through all the indexes and multiplies the matrices
  # If there are invalid dimensions, throw an exception
  try:
    while (i < len(npArrays)):

      # Shape returns dimensions of matrix
      if npArrays[i].shape[0] == npArrays[i].shape:
        npArrays[i] = npArrays[i].reshape(npArrays[i].shape[0], 1)
      
      res = res@npArrays[i]
      #res = res.dot((npArrays[i]))
      i = i + 1

  except:
    print("the following arrays are not compatible:", end="\n\n")
    print(npArrays[i], end="\n\n")
    print(npArrays[i], end="\n\n")
    return None

  else: 
    return res

$$The \,following\, is\, an\, example\, of\, how\, matrix\, multiplication\, works: \\
\begin{bmatrix}
    a  &  b      \\
    c  &  d
\end{bmatrix}
\times
\begin{bmatrix}
    e  &  f  &  g      \\
    h  &  i  &  j 
\end{bmatrix}
=
\begin{bmatrix}
    (a \times e) + (b \times h)  &  (a \times f) + (b \times i)  &  (a \times g) + (b \times j)      \\
    (c \times e) + (d \times h)  &  (c \times f) + (d \times i)  &  (c \times g) + (d \times j)      \\
\end{bmatrix}$$

In [33]:
# Multiplying 2 identical matrices of 1's
arr1 = np.ones((2,4), dtype=int)
arr2 = np.ones((4,2), dtype=int)
combinedArray = [arr1, arr2]
print (multiply_matrices(combinedArray))

[[4 4]
 [4 4]]


In [34]:
# Multiplying 3 3x3 matrices
arr1 = np.array([(10,20,30), (40,50,60), (70,80,90)])
arr2 = np.array([(10,20,30), (40,50,60), (70,80,90)])
arr3 = np.array([(10,20,30), (40,50,60), (70,80,90)])
combinedArray = [arr1,arr2,arr3]

print(multiply_matrices(combinedArray))

[[ 468000  576000  684000]
 [1062000 1305000 1548000]
 [1656000 2034000 2412000]]


In [39]:
# Multiplying 1x2 and 2x1
arr1 = np.array([5, 10])
arr2 = np.array([(5), (10)])
combinedArray = [arr1,arr2]

print(multiply_matrices(combinedArray))

125


In [49]:
# Multiplying 1x2 and 2x1
arr1 = np.array([(5,10)])
arr2 = np.array([(15), (20)])
combinedArray = [arr1,arr2]

print(multiply_matrices(combinedArray))

[275]


In [46]:
# Invalid Multiplication of Matrices
arr1 = np.array([(10,20,30, 40), (40,50,60, 70), (70,80,90, 100)])
arr2 = np.array([(10,20,30), (40,50,60), (70,80,90)])
arr3 = np.array([(10,20,30), (40,50,60), (70,80,90)])
combinedArray = [arr1,arr2,arr3]

print(multiply_matrices(combinedArray))

the following arrays are not compatible:

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

None
